### ISSUE TITLE
Unable to load the group or subscription 

### ISSUE THREAD

**Issue by bibin-v2020** [jonjomckay/fritter#151]
Upgraded to v2.10.0+20210615. Now I'm unable to load the group/subscription. Already tried clearing the cache and stopped the application as well.

Report
========================
Error:

Instance of 'ManuallyReportedException'

Stack trace:

#0 new Subscription.fromMap (package:fritter/database/entities.dart:41)
#1 SubscriptionGroupScreenContent._findSubscriptionGroup.<anonymous closure> (package:fritter/group/group_screen.dart:20)
#2 MappedListIterable.elementAt (dart:_internal/iterable.dart:412)
#3 ListIterator.moveNext (dart:_internal/iterable.dart:341)
#4 new _List._ofEfficientLengthIterable (dart:core-patch/array.dart:93)
#5 new _List.of (dart:core-patch/array.dart:55)
#6 new List.of (dart:core-patch/array_patch.dart:52)
#7 SetMixin.toList (dart:collection/set.dart:118)
#8 HomeModel.listSubscriptions (package:fritter/home_model.dart:153)
<asynchronous suspension>
#9 _FutureBuilderState._subscribe.<anonymous closure> (package:flutter/src/widgets/async.dart)
<asynchronous suspension>
========================

**Comment by bibin-v2020** [comment]
It's fixed somehow.. Thanks for the update
