### ISSUE TITLE
Unable to import data

### ISSUE THREAD

**Issue by ObviousSimple** [jonjomckay/fritter#168]
After exporting my data in order to do a factory reset to my phone, I re-installed the app and tried to import the file but it doesn't load anything

**Comment by jonjomckay** [comment]
Please could you let me know which version of Fritter you're using? It should be in the Bug Report template. It sounds like you're running into #155, but that was fixed in v2.11.0

**Comment by DocSniper** [comment]
The OP is probably right, problem #155 doesn't really seem to have been fixed. I am currently testing 2.11.1, but errors occur in various constellations. Since an update from 2.9 to 2.10 or 2.11.x only leads to crashes for me, I tried to import the exported subscriptions from 2.9 into 2.11.1. But nothing happens and there is no error message. On immediate export right after this import, the JSON file is empty except for the basic 108 bytes.

```
{"settings":null,"subscriptions":[],"subscriptionGroups":null,"subscriptionGroupMembers":null,"tweets":null}
```

Here is the logcat that is created during the import:

```
06-19 13:57:06.678 E/Layer   (905): [Surface(name=AppWindowToken{e0f8339 token=Token{83cbf00 ActivityRecord{6c40183 u0 com.jonjomckay.fritter/.MainActivity t10606}}})/@0x8be433a - animation-leash#0] No local sync point found
06-19 13:57:06.701 E/Layer   (905): [Surface(name=AppWindowToken{e0f8339 token=Token{83cbf00 ActivityRecord{6c40183 u0 com.jonjomckay.fritter/.MainActivity t10606}}})/@0x8be433a - animation-leash#0] No local sync point found
06-19 13:57:12.722 D/FilePickerWritable(31038): onActivityResult(40832, -1, content://com.android.externalstorage.documents/document/primary%3ASniper%2FSync%2Ffritter-2021-06-15.json)
06-19 13:57:12.730 D/FilePickerWritable(31038): Got result content://com.android.externalstorage.documents/document/primary%3ASniper%2FSync%2Ffritter-2021-06-15.json
06-19 13:57:12.750 D/FilePickerWritable(31038): Display Name: fritter-2021-06-15.json
06-19 13:57:12.751 D/FilePickerWritable(31038): Copy file content://com.android.externalstorage.documents/document/primary%3ASniper%2FSync%2Ffritter-2021-06-15.json to /data/user/0/com.jonjomckay.fritter/cache/fritter-2021-06-15.j871824598103894463.tmp
06-19 13:57:12.769 E/flutter (31038): #0      new Subscription.fromMap (package:fritter/database/entities.dart:44)
06-19 13:57:12.769 E/flutter (31038): #1      new SettingsData.fromJson.<anonymous closure(package:fritter/settings/settings_data.dart:38)
06-19 13:57:12.769 E/flutter (31038): #8      new SettingsData.fromJson (package:fritter/settings/settings_data.dart:38)
06-19 13:57:12.769 E/flutter (31038): #9      _OptionsScreenState._importFromFile (package:fritter/options.dart:54)
06-19 13:57:12.769 E/flutter (31038): #10     _OptionsScreenState.build.<anonymous closure>.<anonymous closure>.<anonymous closure(package:fritter/options.dart:340)
06-19 13:57:12.769 E/flutter (31038): #11     _OptionsScreenState.build.<anonymous closure>.<anonymous closure>.<anonymous closure(package:fritter/options.dart:339)
06-19 13:57:12.769 E/flutter (31038): #13     _OptionsScreenState.build.<anonymous closure>.<anonymous closure(package:fritter/options.dart:339)
06-19 13:57:14.191 E/Layer   (905): [Surface(name=AppWindowToken{e0f8339 token=Token{83cbf00 ActivityRecord{6c40183 u0 com.jonjomckay.fritter/.MainActivity t10606}}})/@0x8be433a - animation-leash#0] No local sync point found
06-19 13:57:14.191 E/Layer   (905): [Surface(name=AppWindowToken{e0f8339 token=Token{83cbf00 ActivityRecord{6c40183 u0 com.jonjomckay.fritter/.MainActivity t10606}}})/@0x8be433a - animation-leash#0] No local sync point found
```

**Comment by ObviousSimple** [comment]
I used the fdroid version 2.10.0 but now that i installed 2.11.2 from github, the import was successful

**Comment by DocSniper** [comment]
Just tried again, with 2.11.2 the import now also works for me 😀

**Comment by jonjomckay** [comment]
Great, thanks for confirming!
